base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2

automl:
  framework: h2o
  max_runtime_secs: 3600 
  max_models: 20 
  stopping_metric: AUC  
  include_algos:  
    - GLM
    - GBM
    - XGBoost
    - DRF

model_dir: saved_models

reports:
  leaderboard: report/leaderboard.csv  # Store leaderboard of models
  best_model: saved_models/best_model  # Path to save the best model
